name: Push Docker Image

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: emoine
  HOST: emoine.trap.jp

jobs:
  image:
    name: Build Docker Image (master)
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: HOST={{ env.HOST }}
          tags: |
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:latest
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}